export default {
  login: 'mohmmedabdelaal',
  id: 56766145,
  node_id: 'MDQ6VXNlcjU2NzY2MTQ1',
  avatar_url: 'https://avatars.githubusercontent.com/u/56766145?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/mohmmedabdelaal',
  html_url: 'https://github.com/mohmmedabdelaal',
  followers_url: 'https://api.github.com/users/mohmmedabdelaal/followers',
  following_url:
    'https://api.github.com/users/mohmmedabdelaal/following{/other_user}',
  gists_url: 'https://api.github.com/users/mohmmedabdelaal/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/mohmmedabdelaal/starred{/owner}{/repo}',
  subscriptions_url:
    'https://api.github.com/users/mohmmedabdelaal/subscriptions',
  organizations_url: 'https://api.github.com/users/mohmmedabdelaal/orgs',
  repos_url: 'https://api.github.com/users/mohmmedabdelaal/repos',
  events_url: 'https://api.github.com/users/mohmmedabdelaal/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/mohmmedabdelaal/received_events',
  type: 'User',
  site_admin: false,
  name: 'Mohamed abdelaal',
  company: null,
  blog: 'mohamedabdelaal',
  location: 'Port said, Egypt',
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 44,
  public_gists: 0,
  followers: 0,
  following: 8,
  created_at: '2019-10-19T15:24:35Z',
  updated_at: '2022-06-24T05:52:41Z',
};
